fix: add a port check while parsing Origin
flamego/cors pull request #19
Opened 2022-04-06 15:20 UTC by m1dsummer

A fix for https://github.com/flamego/flamego/issues/116

2022-04-08 12:42 UTC, unknwon requested changes
Please follow the original pull request template.

2022-04-09 14:52 UTC, unknwon requested changes
Thanks for the follow up!

One last problem to address.

2022-04-09 14:52 UTC, unknwon commented on cors_test.go
> +		},
I think we need another test case which `http://example.com:8080` is allowed.

2022-04-09 16:30 UTC, m1dsummer commented on cors_test.go
> +		},
> I think we need another test case which `http://example.com:8080` is allowed.

yeah, maybe the test case is too simple🤣

2022-04-10 08:21 UTC, unknwon approved these changes

2022-04-10 08:21 UTC, merged

2022-04-10 08:22 UTC, unknwon commented
https://github.com/flamego/cors/releases/tag/v1.0.1 has been tagged for this merge.