cors: initial implementation
flamego/cors pull request #2
Opened 2021-07-31 12:06 UTC by Moesang

2021-07-31 13:05 UTC, wuhan005 requested changes

2021-07-31 13:05 UTC, wuhan005 commented on cors.go
> +		}
```suggestion
```

2021-07-31 13:05 UTC, wuhan005 commented on cors.go
> +		}
```suggestion
```

2021-07-31 13:05 UTC, wuhan005 commented on cors.go
> +	} else {
```suggestion
	}
```

2021-07-31 13:05 UTC, wuhan005 commented on cors.go
> +	}
```suggestion
```

2021-07-31 13:05 UTC, wuhan005 commented on cors.go
> +			ok := false
```suggestion
			var ok bool
```

2021-07-31 13:05 UTC, wuhan005 commented on cors.go
> +			ctx.ResponseWriter().WriteHeader(200) // return response
```suggestion
			ctx.ResponseWriter().WriteHeader(http.StatusOK)
```

2021-07-31 13:05 UTC, wuhan005 commented on cors_test.go
> +	req, err := http.NewRequest(http.MethodGet, "/", strings.NewReader("some request"))
```suggestion
	req, err := http.NewRequest(http.MethodGet, "/", nil)
```

2021-07-31 14:20 UTC, unknwon commented on README.md
> +}
<img width="413" alt="CleanShot 2021-07-31 at 22 20 33@2x" src="https://user-images.githubusercontent.com/2946214/127742759-cb107d75-73db-4270-98ad-58112392313e.png">

Mixed use of tabs and spaces.

2021-07-31 14:21 UTC, unknwon commented on cors.go
> +*/
```suggestion
/*
Options to configure the CORS middleware read from the [cors] section of the ini configuration file.
SCHEME may be http or https as accepted schemes or the '*' wildcard to accept any scheme.
ALLOW_DOMAIN may be a comma separated list of domains that are allowed to run CORS requests
Special values are the  a single '*' wildcard that will allow any domain to send requests without
credentials and the special '!*' wildcard which will reply with requesting domain in the 'access-control-allow-origin'
header and hence allow requests from any domain *with* credentials.
ALLOW_SUBDOMAIN set to true accepts requests from any subdomains of ALLOW_DOMAIN.
METHODS may be a comma separated list of HTTP-methods to be accepted.
MAX_AGE_SECONDS may be the duration in secs for which the response is cached (default 600).
ref: https://stackoverflow.com/questions/54300997/is-it-possible-to-cache-http-options-response?noredirect=1#comment95790277_54300997
ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age
ALLOW_CREDENTIALS set to false rejects any request with credentials.
*/
```

Use `//` for comments almost always.

2021-07-31 14:43 UTC, unknwon commented on README.md
> +}
```suggestion
package main

import (
	"github.com/flamego/flamego"
	"github.com/flamego/cors"
)

func main() {
	f := flamego.Classic()
	f.Use(cors.CORS())
	f.Get("/", func(c flamego.Context) string {
		return "ok"
	})
	f.Run()
}
```

2021-07-31 14:45 UTC, unknwon commented on cors.go
> +
```suggestion
```

2021-07-31 14:45 UTC, unknwon commented on cors.go
> +	AllowCredentials bool
We need docstring for every public field.

2021-07-31 14:46 UTC, unknwon commented on cors.go
> +			"access-control-allow-methods": strings.Join(opt.Methods, ","),
```suggestion
			"Access-Control-Allow-Methods": strings.Join(opt.Methods, ","),
```

2021-07-31 14:47 UTC, unknwon commented on cors.go
> +}
Why can't we simply use `http.Error` and remove this function?

2021-08-08 13:40 UTC, unknwon requested changes

2021-08-08 13:40 UTC, unknwon commented on README.md
> +	"github.com/flamego/cors"
```suggestion
	"github.com/flamego/cors"
	"github.com/flamego/flamego"
```

`c` is before `f`, and I think this is what `gofmt` would resort for us.

2021-08-08 13:40 UTC, unknwon commented on cors.go
> +// ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age
```suggestion
// Options contains options for the corS.CORS middleware.
```

2021-08-08 13:40 UTC, unknwon commented on cors.go
> +	AllowCredentials bool
```suggestion
	// Scheme may be http or https as accepted schemes or the '*' wildcard to accept any scheme.
	Scheme string
	// AllowDomains is a comma separated list of domains that are allowed to run CORS requests
	// Special values are the  a single '*' wildcard that will allow any domain to send requests without
	// credentials and the special '!*' wildcard which will reply with requesting domain in the 'access-control-allow-origin'
	// header and hence allow requests from any domain *with* credentials.
	AllowDomains []string
	// AllowSubdomain allowed ???
	AllowSubdomain bool
	// Methods is a comma separated list of HTTP-methods to be accepted.
	Methods []string
	// MaxAgeSeconds is the duration in secs for which the response is cached (default 600).
	MaxAgeSeconds int
	// AllowCredentials set to false rejects any request with credentials.
	AllowCredentials bool
```

1. Please finish the incomplete sentence.
2. Please describe what are the default values for each field if left unset.

2021-08-08 13:40 UTC, unknwon commented on cors.go
> +			http.MethodOptions,
Why is all of these methods necessary as the default list?

2021-08-08 16:40 UTC, Moesang commented on cors.go
> +			http.MethodOptions,
The list has remaind only GET, POST and OPTIONS now.

2021-08-09 02:45 UTC, unknwon requested changes

2021-08-09 02:45 UTC, unknwon commented on cors.go
> +const anyDomain = "!*"
Why does this constant needs to be defined as global?

2021-08-09 02:45 UTC, unknwon commented on cors.go
> +	Scheme string
```suggestion
	// Scheme may be http or https as accepted schemes or the '*' wildcard to accept any scheme. Default is "http".
	Scheme string
```

Please take a look at how field docstring is written in other Options:

https://github.com/flamego/flamego/blob/eff1d929e6ce0aadc12c1493918d02bdb0d04798/render.go#L33-L42

Same for other fields in the struct.

2021-08-09 02:45 UTC, unknwon commented on cors.go
> +	MaxAgeSeconds int
```suggestion
	MaxAge time.Duration
```

I think this is much easier to use in Go, and when we use it, we just call `MaxAge.Seconds()`

2021-08-09 02:45 UTC, unknwon commented on cors.go
> +	if len(opt.Scheme) == 0 {
```suggestion
	if opt.Scheme == "" {
```

The idiomatic Go is to compare with empty string when checking if the string is empty.

2021-08-09 02:45 UTC, unknwon commented on cors.go
> +// https://fetch.spec.whatwg.org/#cors-protocol-and-credentials
```suggestion
// CORS returns a middleware handler that responds to preflight requests with adequate "Access-Control-*" response headers.
```

2021-08-09 02:45 UTC, unknwon commented on cors.go
> +	return func(ctx flamego.Context, log *log.Logger) {
Seem we're not using `log *log.Logger` at all, can we remove it?

2021-08-09 02:45 UTC, unknwon commented on cors.go
> +			ctx.ResponseWriter().WriteHeader(http.StatusOK) // return response
Why do we only write response code for OPTIONS method? What about other methods (e.g. GET, POST)?

2021-08-09 05:07 UTC, Moesang commented on cors.go
> +			ctx.ResponseWriter().WriteHeader(http.StatusOK) // return response
A CORS-preflight request method is OPTIONS, it seems not required to response other methods. 
reference: https://fetch.spec.whatwg.org/#cors-preflight-fetch

2021-08-09 06:13 UTC, unknwon commented on cors.go
> +			ctx.ResponseWriter().WriteHeader(http.StatusOK) // return response
If that's the case, why would we want to continue if it's not a OPTIONS request? Can't we just return here?

2021-08-10 12:02 UTC, unknwon requested changes
Thanks for the followup!

Left some more comments, and looking at tests, I'm certain many cases are not tested, please take some thoughts to improve :)

2021-08-10 12:02 UTC, unknwon commented on cors.go
> +			}
```suggestion
			if !ok {
				http.Error(ctx.ResponseWriter(), fmt.Sprintf("CORS request from prohibited domain %v", origin), http.StatusBadRequest)
				return
			}

			if opt.Scheme != "*" {
				u.Scheme = opt.Scheme
			}
			headers["Access-Control-Allow-Origin"] = u.String()
			headers["Access-Control-Allow-Credentials"] = strconv.FormatBool(opt.AllowCredentials)
			headers["Vary"] = "Origin"
```

2021-08-10 12:02 UTC, unknwon commented on cors_test.go
> +// Package cors is a middleware that generates CORS headers for Flamego.
```suggestion
```

2021-08-10 12:02 UTC, unknwon commented on cors_test.go
> +	"github.com/stretchr/testify/assert"
```suggestion
	"github.com/stretchr/testify/assert"

	"github.com/flamego/flamego"
```

2021-08-11 04:52 UTC, unknwon requested changes

2021-08-11 04:52 UTC, unknwon commented on cors_test.go
> +	f2 := flamego.NewWithLogger(&bytes.Buffer{})
Why not put this set of tests in a separate function instead of naming it `f2`?

2021-08-11 04:52 UTC, unknwon commented on cors_test.go
> +			name:   "Error method",
```suggestion
			name:   "error method",
```

2021-08-11 04:52 UTC, unknwon commented on cors_test.go
> +			name:   "Default cors response",
```suggestion
			name:   "default response",
```

2021-08-11 04:52 UTC, unknwon commented on cors_test.go
> +	defaultTests := []struct {
```suggestion
	tests := []struct {
```

2021-08-11 04:52 UTC, unknwon commented on cors_test.go
> +				assert.Equal(t, headerValue, resp.Header().Get(headerKey))
Is `assert.Equal` not working for comparing maps?

2021-08-11 04:52 UTC, unknwon commented on cors_test.go
> +		respHeaders map[string]string
```suggestion
		wantHeaders map[string]string
```

2021-08-11 04:52 UTC, unknwon commented on cors_test.go
> +			statueCode: 200,
```suggestion
			statueCode: http.StatusOK,
```

2021-08-11 06:06 UTC, unknwon approved these changes
One last minor comment, approve to unblock.

2021-08-11 06:06 UTC, unknwon commented on cors_test.go
> +		statueCode  int
```suggestion
		wantCode  int
```

2021-08-11 06:20 UTC, wuhan005 requested changes

2021-08-11 06:20 UTC, wuhan005 commented on cors.go
> +			"Access-Control-Max-Age":       fmt.Sprintf("%.0f", opt.MaxAge.Seconds()),
```go
fmt.Printf("%.0f", 123.456)
```
You will get `1230` here,

Why not simply use `strconv.Itoa(int(a.Seconds()))` instead?

2021-08-11 06:24 UTC, wuhan005 commented on cors.go
> +			"Access-Control-Max-Age":       fmt.Sprintf("%.0f", opt.MaxAge.Seconds()),
Or a better way to convert `float64` to `int`:
```
strconv.FormatFloat(123.4567890, 'f', 0, 64)// 123
```

FYI: https://pkg.go.dev/strconv#FormatFloat

2021-08-11 06:26 UTC, Moesang commented on cors.go
> +			"Access-Control-Max-Age":       fmt.Sprintf("%.0f", opt.MaxAge.Seconds()),
```
fmt.Printf("%.0f", 123.456)
```
Out put is `123` not `1230`.

2021-08-11 06:32 UTC, wuhan005 commented on cors.go
> +			"Access-Control-Max-Age":       fmt.Sprintf("%.0f", opt.MaxAge.Seconds()),
Oops, my mistake.
I got some messy output in my Go playground. 😓

2021-08-11 06:59 UTC, wuhan005 approved these changes

2021-08-11 07:06 UTC, merged